version: "3.8"
services:
  flask:
      build:
        context: GroupDriveServer
        dockerfile: Dockerfile
      container_name: flask
      image: groupdrive-server
      restart: unless-stopped
      depends_on:
        - mongodb

  mongodb:
    build:
        context: mongodb
        dockerfile: Dockerfile
    image : groupdrive-mongo
    container_name: mongodb
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - './mongodb/database:/data/db'
    ports:
    - 27017:27017
    restart: unless-stopped
